name: "Slideshow paragraph"
description: "Slideshow paragraph recipe for UBC Web Services websites"
type: "Paragraph type"
recipes:
  - recipes/ws-recipes/paragraphs/paragraph-slide
  - recipes/ws-recipes/paragraphs/paragraph-shared-fields
install:
    # core
  - file
  - link
  - taxonomy
  # contrib
  - field_group
  - paragraphs
  - ubc_paragraph_entities
