
name: "Science Event type configuration"
description: "Science Event type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - datetime
  - image
  - link
  - menu_ui
  - node
  - options
  - path
  - responsive_image
  - taxonomy
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - field_group
  - focal_point
  - maxlength
  - metatag
  - pathauto
  - scheduler
  - simple_sitemap
  - text_summary_options
config:
  actions:
    # update the image field
    field.field.node.ubc_event.field_event_image:
      simple_config_update:
        description: 'Add a feature image to the announcement. Feature image must be at least 980x653.'
        settings.file_extensions: 'png jpg jpeg'
        settings.max_resolution: ''
        settings.min_resolution: '980x653'
    # update the form display
    core.entity_form_display.node.ubc_event.default:
      simple_config_update:
        third_party_settings.field_group.group_metadata.children:
          - field_event_category
          - field_event_media_contact
          - field_event_tags
      setComponents:
        -
          name: body
          options:
            type: text_textarea_with_summary
            weight: 4
            region: content
            settings:
              rows: 9
              placeholder: ''
              summary_rows: 3
              show_summary: true
            third_party_settings:
              maxlength:
                maxlength_js: ''
                maxlength_js_label: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
                maxlength_js_summary: 160
                maxlength_js_label_summary: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
                maxlength_js_enforce: true
                maxlength_js_truncate_html: false
              allowed_formats:
                hide_help: 0
                hide_guidelines: 0
        -
          name: field_event_link
          options:
            type: link_default
            weight: 5
            region: content
            settings:
              placeholder_url: ''
              placeholder_title: ''
            third_party_settings:
              maxlength:
                maxlength_js: 100
                maxlength_js_label: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
        -
          name: field_event_image_caption
          options:
            type: string_textfield
            weight: 2
            region: content
            settings:
              size: 60
              placeholder: 'Add a caption to the feature image if applicable.'
            third_party_settings:
              maxlength:
                maxlength_js: 150
                maxlength_js_label: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
        -
          name: field_event_media_contact
          options:
            type: options_select
            weight: 10
            region: content
            settings: {  }
            third_party_settings: {  }
        -
          name: field_event_cost
          options:
            type: string_textfield
            weight: 6
            label: hidden
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_event_is_virtual
          options:
            type: boolean_checkbox
            weight: 5
            region: content
            settings:
              display_label: true
            third_party_settings: {  }
    # update the default display
    core.entity_view_display.node.ubc_event.default:
      simple_config_update:
        third_party_settings.field_group.group_metadata.children:
          - field_event_category
          - field_event_media_contact
          - field_event_tags
      setComponents:
        -
          name: field_event_media_contact
          options:
            type: entity_reference_label
            label: hidden
            weight: 8
            region: content
            settings:
              link: false
            third_party_settings: { }
        -
          name: field_event_cost
          options:
            type: string
            weight: 7
            region: content
            settings:
              link_to_entity: false
            third_party_settings: { }
        -
          name: field_event_is_virtual
          options:
            type: boolean
            label: above
            weight: 6
            region: content
            settings:
              format: default
              format_custom_false: ''
              format_custom_true: ''
            third_party_settings: { }
    # update the featured content display
    core.entity_view_display.node.ubc_event.featured_content:
      simple_config_update:
        content.field_event_image.settings.responsive_image_style: masthead_focal_point
      setComponent:
        name: field_event_image_caption
        options:
          type: string
          weight: 1
          region: content
          label: hidden
          settings:
            link_to_entity: false
          third_party_settings: {  }
    # update the teaser display
    core.entity_view_display.node.ubc_event.teaser:
      setComponent:
        name: field_event_external_link
        options:
          type: link
          weight: 2
          region: content
          label: hidden
          settings:
            trim_length: 80
            url_only: false
            url_plain: false
            rel: ''
            target: ''
          third_party_settings: {  }
    # assign ubc_event permissions
    user.role.manager:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: manager
        label: 'Manager'
        weight: 7
        is_admin: false
      grantPermissions:
        - 'create ubc_event content'
        - 'delete any ubc_event content'
        - 'delete own ubc_event content'
        - 'delete ubc_event revisions'
        - 'edit any ubc_event content'
        - 'edit own ubc_event content'
        - 'revert ubc_event revisions'
        - 'view ubc_event revisions'
        - 'create terms in event_category'
        - 'delete terms in event_category'
        - 'edit terms in event_category'