name: "Super User role"
description: "Super User recipe for UBC Web Services websites"
type: "Super User role"
install:
  # core
  - block
  - contextual
  - file
  - menu_ui
  - path
  - pathauto
  - taxonomy
  - toolbar
  - user
config:
  actions:
    user.role.super_user:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: super_user
        label: 'Super User'
        weight: 7
        is_admin: false
      # grant permissions from enabled core modules
      grantPermissions:
        - 'access administration pages'
        - 'access block library'
        - 'access content overview'
        - 'access contextual links'
        - 'access files overview'
        - 'access site in maintenance mode'
        - 'access taxonomy overview'
        - 'access toolbar'
        - 'access user profiles'
        - 'administer blocks'
        - 'administer content types'
        - 'administer menu'
        - 'administer node display'
        - 'administer node fields'
        - 'administer node form display'
        - 'administer nodes'
        - 'administer pathauto'
        - 'administer site configuration'
        - 'administer taxonomy'
        - 'administer themes'
        - 'administer url aliases'
        - 'administer users'
        - 'administer views'
        - 'bulk delete aliases'
        - 'bulk update aliases'
        - 'cancel account'
        - 'change own username'
        - 'create url aliases'
        - 'delete any file'
        - 'notify of path changes'
        - 'select account cancellation method'
        - 'view the administration theme'