name: "General media configuration"
description: "General media configuration recipe for UBC Web Services websites"
type: "Media configuration"
recipes:
  - recipes/ws-recipes/media/media-view-modes
  - recipes/ws-recipes/media/media-type-audio
  - recipes/ws-recipes/media/media-type-file
  - recipes/ws-recipes/media/media-type-image
  - recipes/ws-recipes/media/media-type-private-file
  - recipes/ws-recipes/media/media-type-remote-video
  - recipes/ws-recipes/media/media-type-svg-icon
install:
  # contrib
  - crop
  - dropzonejs
  - image_widget_crop
  - media_bulk_upload_dropzonejs
  - media_alias_display
  - media_bulk_upload
  - media_entity_file_replace
