name: "Orchestrate all recipes"
description: "Orchestrate all recipes for UBC Web Services websites"
type: "Site"
recipes:
  # install parent recipes first
  - recipes/ws-recipes/role/role-editor
  - recipes/ws-recipes/role/role-content-creator
  - recipes/ws-recipes/theme/theme-ws
  - recipes/ws-recipes/theme/theme-admin
  - recipes/ws-recipes/block/block-code
  - recipes/ws-recipes/block/block-quicklinks
  - recipes/ws-recipes/date-formats
  - recipes/ws-recipes/image/image-styles
  # install recipes that rely on other recipes next
  - recipes/ws-recipes/image/image-styles-responsive
  - recipes/ws-recipes/taxonomy/taxonomy-admin
  - recipes/ws-recipes/media/media-config
  - recipes/ws-recipes/text-format/text-format-filtered
  - recipes/ws-recipes/custom-entity/custom-entity-ubc-alert
  - recipes/ws-recipes/paragraphs/paragraph-config
  - recipes/ws-recipes/node/node-ubc-announcement
  - recipes/ws-recipes/node/node-ubc-event
  - recipes/ws-recipes/node/node-ubc-homepage
  - recipes/ws-recipes/node/node-ubc-landing-page
  - recipes/ws-recipes/node/node-ubc-page
  - recipes/ws-recipes/node/node-ubc-private-page
  - recipes/ws-recipes/node/node-ubc-profile
install:
  # contrib
  - role_delegation
  - view_unpublished
config:
  actions:
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 1
        is_admin: false
      # grant permissions from enabled core modules
      grantPermissions:
        - 'view any unpublished content'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 2
        is_admin: false
      # grant permissions from enabled core modules
      grantPermissions:
        - 'assign content_creator role'
        - 'assign editor role'
        - 'view any unpublished content'