name: "UBC Alert type"
description: "UBC Alert type recipe for UBC Web Services websites"
type: "Content item type"
install:
  # core
  - ckeditor5
  - options
  - taxonomy
  - text
  - views
  - user
  # contrib
  - auto_entitylabel
  - datetime
  - maxlength
  - ubc_content_items
config:
  actions:
    user.role.anonymous:
      grantPermissions:
        - 'view published content item entities'
    user.role.authenticated:
      grantPermissions:
        - 'view published content item entities'
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      # grant permissions from enabled core modules
      grantPermissions:
        - 'view published content item entities'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      # grant permissions from enabled core modules
      grantPermissions:
        - 'add content item entities'
        - 'delete content item entities'
        - 'delete all content item revisions'
        - 'edit content item entities'
        - 'revert all content item revisions'
        - 'view all content item revisions'
        - 'view published content item entities'
        - 'view unpublished content item entities'
