name: "Private Page type configuration"
description: "Private Page type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - file
  - menu_ui
  - node
  - path
  - text
  - user
  # contrib
  - scheduler
config:
  # assign private page permissions
  actions:
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create private_page content'
        - 'delete any private_page content'
        - 'delete own private_page content'
        - 'delete private_page revisions'
        - 'edit any private_page content'
        - 'edit own private_page content'
        - 'revert private_page revisions'
        - 'view private_page revisions'
