name: "Guide type configuration"
description: "Guide type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - link
  - menu_ui
  - node
  - options
  - path
  - taxonomy
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - entity_reference_revisions
  - field_group
  - maxlength
  - metatag
  - paragraphs
  - pathauto
  - scheduler
  - simple_sitemap
  - text_summary_options
config:
  actions:
    # assign ubc_partner_organization permissions
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      grantPermissions:
        - 'create guide content'
        - 'delete own guide content'
        - 'delete guide revisions'
        - 'edit own guide content'
        - 'revert guide revisions'
        - 'view guide revisions'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create guide content'
        - 'delete any guide content'
        - 'delete own guide content'
        - 'delete guide revisions'
        - 'edit any guide content'
        - 'edit own guide content'
        - 'revert guide revisions'
        - 'view guide revisions'
        - 'create terms in documentation_type'
        - 'delete terms in documentation_type'
        - 'edit terms in documentation_type'
    user.role.manager:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: manager
        label: 'Manager'
        weight: 7
        is_admin: false
      grantPermissions:
        - 'create guide content'
        - 'delete any guide content'
        - 'delete own guide content'
        - 'delete guide revisions'
        - 'edit any guide content'
        - 'edit own guide content'
        - 'revert guide revisions'
        - 'view guide revisions'
        - 'create terms in documentation_type'
        - 'delete terms in documentation_type'
        - 'edit terms in documentation_type'

