name: "Slideshow paragraph"
description: "Slideshow paragraph recipe for UBC Web Services websites"
type: "Paragraph type"
recipes:
  - ../recipes/ws-recipes/ws-core/paragraphs/paragraph-slide
install:
    # core
  - file
  - link
  - taxonomy
  # contrib
  - field_group
  - paragraphs
  - ubc_paragraph_entities
