name: "Audio media type"
description: "Audio media type recipe for UBC Web Services websites"
type: "Media"
recipes:
  - recipes/ws-recipes/role/role-editor
  - core/recipes/audio_media_type
  - recipes/ws-recipes/media/media-view-modes
install:
  # core
  - file
  - image
  - media
  - path
config:
  # assign audio media permissions
  actions:
    user.role.editor:
      grantPermissions:
        - 'create audio media'
        - 'delete any audio media'
        - 'delete own audio media'
        - 'edit any audio media'
        - 'edit own audio media'
        - 'view any audio media revisions'
        - 'delete any audio media revisions'
        - 'revert any audio media revisions'
