name: "Slide paragraph"
description: "Slide paragraph recipe for UBC Web Services websites"
type: "Paragraph type"
install:
    # core
  - file
  - image
  - link
  - responsive_image
  - taxonomy
  # contrib
  - focal_point
  - maxlength
  - paragraphs
  - ubc_paragraph_entities
