name: "General media configuration"
description: "General media configuration recipe for UBC Web Services websites"
type: "Media configuration"
recipes:
  - ../recipes/ws-recipes/ws-sci/media/media-line-art
install:
  # core
  - media
  - user
  # contrib
  - crop
  - dropzonejs
  - image_widget_crop
  - media_bulk_upload_dropzonejs
  - media_alias_display
  - media_bulk_upload
  - media_entity_file_replace
  - svg_image
config:
  actions:
    # Update media form modes config
    core.entity_form_display.media.image.default:
      setComponents:
        -
          name: name
          options:
            type: string_textfield
            weight: 2
            region: content
            settings:
              link: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: replace_file
          options:
            weight: 3
            region: content
            settings: { }
            third_party_settings: {  }
    core.entity_form_display.media.private_file.default:
      setComponent:
        name: replace_file
        options:
          weight: 3
          region: content
          settings: { }
          third_party_settings: {  }
    # update media bulk upload settings
    media_bulk_upload.media_bulk_config.bulk_upload_documents:
      simple_config_update:
        label: Bulk Upload Files
    user.role.manager:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: manager
        label: Manager
        weight: 7
        is_admin: false
      grantPermissions:
        - 'access media overview'
        - 'delete any media'
        - 'delete media'
        - 'dropzone upload files'
        - 'update any media'
        - 'update media'
        - 'use bulk_upload_documents bulk upload form'
        - 'use bulk_upload_images bulk upload form'
        - 'view all media revisions'
        - 'view media'
        - 'view own unpublished media'
        - 'create audio media'
        - 'delete any audio media'
        - 'delete own audio media'
        - 'edit any audio media'
        - 'edit own audio media'
        - 'view any audio media revisions'
        - 'delete any audio media revisions'
        - 'revert any audio media revisions'
        - 'create file media'
        - 'delete any file media'
        - 'delete own file media'
        - 'edit any file media'
        - 'edit own file media'
        - 'view any file media revisions'
        - 'delete any file media revisions'
        - 'revert any file media revisions'
        - 'create image media'
        - 'delete any image media'
        - 'delete own image media'
        - 'edit any image media'
        - 'edit own image media'
        - 'view any image media revisions'
        - 'delete any image media revisions'
        - 'revert any image media revisions'
        - 'create private_file media'
        - 'delete any private_file media'
        - 'delete own private_file media'
        - 'edit any private_file media'
        - 'edit own private_file media'
        - 'view any private_file media revisions'
        - 'delete any private_file media revisions'
        - 'revert any private_file media revisions'
        - 'create remote_video media'
        - 'delete any remote_video media'
        - 'delete own remote_video media'
        - 'edit any remote_video media'
        - 'edit own remote_video media'
        - 'view any remote_video media revisions'
        - 'delete any remote_video media revisions'
        - 'revert any remote_video media revisions'
        - 'create svg_icon media'
        - 'delete any svg_icon media'
        - 'delete own svg_icon media'
        - 'edit any svg_icon media'
        - 'edit own svg_icon media'
        - 'view any svg_icon media revisions'
        - 'delete any svg_icon media revisions'
        - 'revert any svg_icon media revisions'
