name: "Science Homepage default content configuration"
description: "Science Homepage default content recipe for UBC Web Services websites"
type: "Content"
recipes:
  - recipes/ws-recipes/portfolio/portfolio-sci/node/node-sci-homepage