
name: "VPR Event type configuration"
description: "VPR Event type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - datetime
  - image
  - link
  - menu_ui
  - node
  - options
  - path
  - responsive_image
  - taxonomy
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - field_group
  - focal_point
  - maxlength
  - metatag
  - pathauto
  - quick_node_clone
  - scheduler
  - simple_sitemap
  - text_summary_options
config:
  actions:
    field.storage.node.field_show_gradient_on_image:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.field_show_gradient_on_image
        field_name: field_show_gradient_on_image
        entity_type: node
        type: boolean
        settings: {  }
        module: core
        locked: false
        cardinality: 1
        translatable: true
        indexes: {  }
        persist_with_no_fields: false
        custom_storage: false
    # add view modes if they aren't present
    core.entity_view_mode.node.card_horizontal:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.card_horizontal
        label: 'Card: Horizontal'
        targetEntityType: node
        cache: true
    core.entity_view_mode.node.card_image:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.card_image
        label: 'Card: Image'
        targetEntityType: node
        cache: true
    core.entity_view_mode.node.card_vertical:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.card_vertical
        label: 'Card: Vertical'
        targetEntityType: node
        cache: true
    core.entity_view_mode.node.featured_content:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.featured_content
        label: 'Featured Content'
        targetEntityType: node
        cache: true
    taxonomy.vocabulary.research_theme:
      createIfNotExists:
        langcode: en
        status: true
        dependencies: {  }
        name: 'Research Theme'
        vid: research_theme
        description: 'Associates the content with a research theme'
        weight: 0
    # assign ubc_event permissions
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 2
        is_admin: false
      grantPermissions:
        - 'clone ubc_event content'
        - 'create terms in research_theme'
        - 'delete terms in research_theme'
        - 'edit terms in research_theme'
    user.role.super_user:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: super_user
        label: 'Super User'
        weight: -5
        is_admin: false
      grantPermissions:
        - 'clone ubc_event content'
        - 'create ubc_event content'
        - 'delete any ubc_event content'
        - 'delete own ubc_event content'
        - 'delete ubc_event revisions'
        - 'edit any ubc_event content'
        - 'edit own ubc_event content'
        - 'revert ubc_event revisions'
        - 'view ubc_event revisions'
        - 'create terms in research_theme'
        - 'delete terms in research_theme'
        - 'edit terms in research_theme'

