name: "Image media type"
description: "Image media type for UBC Web Services websites"
type: "Media type"
recipes:
  - core/recipes/image_media_type
install:
  # core
  - file
  - image
  - media
  - media_library
  - path
  - user
  # contrib
  - crop
config:
  actions:
    # update the path where media is is stored
    field.field.media.image.field_media_image:
      simpleConfigUpdate:
        settings.file_directory: media-uploads/images
    # assign image media permissions
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      grantPermissions:
        - 'create image media'
        - 'delete any image media'
        - 'delete own image media'
        - 'edit any image media'
        - 'edit own image media'
        - 'view any image media revisions'
        - 'delete any image media revisions'
        - 'revert any image media revisions'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create image media'
        - 'delete any image media'
        - 'delete own image media'
        - 'edit any image media'
        - 'edit own image media'
        - 'view any image media revisions'
        - 'delete any image media revisions'
        - 'revert any image media revisions'