name: "Media Contact taxonomy"
description: "Media Contact taxonomy recipe for UBC Web Services websites"
type: "Taxonomy"
install:
  # core
  - taxonomy
  - telephone
  - user
  # contrib
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - pathauto
config:
  # assign media_contact taxonomy permissions
  actions:
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create terms in media_contact'
        - 'delete terms in media_contact'
        - 'edit terms in media_contact'
    user.role.manager:
        # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
        createIfNotExists:
          id: manager
          label: 'Manager'
          weight: 7
          is_admin: false
        grantPermissions:
          - 'create terms in media_contact'
          - 'delete terms in media_contact'
          - 'edit terms in media_contact'