name: "File media type"
description: "File media type recipe for UBC Web Services websites"
type: "Media type"
install:
  # core
  - file
  - media
  - media_library
  - path
  - user
config:
  # assign file media permissions
  actions:
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      grantPermissions:
        - 'create file media'
        - 'delete any file media'
        - 'delete own file media'
        - 'edit any file media'
        - 'edit own file media'
        - 'view any file media revisions'
        - 'delete any file media revisions'
        - 'revert any file media revisions'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create file media'
        - 'delete any file media'
        - 'delete own file media'
        - 'edit any file media'
        - 'edit own file media'
        - 'view any file media revisions'
        - 'delete any file media revisions'
        - 'revert any file media revisions'