name: "Private file media type"
description: "Private file media type for UBC Web Services websites"
type: "Media type"
install:
  # core
  - file
  - media
  - media_library
  - path
  - user
  - ubc_media_entities
config:
  # assign private_file media permissions
  actions:
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      grantPermissions:
        - 'create private_file media'
        - 'delete any private_file media'
        - 'delete own private_file media'
        - 'edit any private_file media'
        - 'edit own private_file media'
        - 'view any private_file media revisions'
        - 'delete any private_file media revisions'
        - 'revert any private_file media revisions'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create private_file media'
        - 'delete any private_file media'
        - 'delete own private_file media'
        - 'edit any private_file media'
        - 'edit own private_file media'
        - 'view any private_file media revisions'
        - 'delete any private_file media revisions'
        - 'revert any private_file media revisions'
