name: "Admin theme"
description: "Admin theme configuration for UBC Web Services websites"
type: "Site"
install:
  - admin_toolbar
  - admin_toolbar_tools
  - gin
  - gin_toolbar
  - gin_login
  - rebuild_cache_access
config:
  import:
    admin_toolbar: "*"
    gin: "*"
    gin_toolbar: "*"
    gin_login: "*"
  actions:
    system.theme:
      simple_config_update:
        admin: gin
