name: "Landing Page type configuration"
description: "Landing Page type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - file
  - image
  - link
  - menu_ui
  - node
  - path
  - taxonomy
  - text
  - user
  # contrib
  - allowed_formats
  - entity_reference_revisions
  - field_group
  - focal_point
  - maxlength
  - metatag
  - paragraphs
  - pathauto
  - responsive_image
  - scheduler
  - simple_sitemap
  - text_summary_options
config:
  actions:
    # add view modes if they aren't present
    core.entity_view_mode.node.card_horizontal:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.card_horizontal
        label: 'Card: Horizontal'
        targetEntityType: node
        cache: true
    core.entity_view_mode.node.card_image:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.card_image
        label: 'Card: Image'
        targetEntityType: node
        cache: true
    core.entity_view_mode.node.card_vertical:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.card_vertical
        label: 'Card: Vertical'
        targetEntityType: node
        cache: true
    core.entity_view_mode.node.custom_content:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.custom_content
        label: 'Custom Content'
        targetEntityType: node
        cache: true
    core.entity_view_mode.node.featured_content:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.featured_content
        label: 'Featured Content'
        targetEntityType: node
        cache: true
    # assign landing page permissions
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 2
        is_admin: false
      grantPermissions:
        - 'create ubc_landing_page content'
        - 'delete any ubc_landing_page content'
        - 'delete own ubc_landing_page content'
        - 'delete ubc_landing_page revisions'
        - 'edit any ubc_landing_page content'
        - 'edit own ubc_landing_page content'
        - 'revert ubc_landing_page revisions'
        - 'view ubc_landing_page revisions'
