
name: "VPR Profile type configuration"
description: "VPR Profile type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - datetime
  - image
  - link
  - menu_ui
  - node
  - options
  - path
  - responsive_image
  - taxonomy
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - field_group
  - focal_point
  - maxlength
  - metatag
  - pathauto
  - quick_node_clone
  - scheduler
  - simple_sitemap
  - text_summary_options
config:
  actions:
    # add view modes if they aren't present
    core.entity_view_mode.node.card_horizontal_round_image:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.card_horizontal_round_image
        label: 'Card: Horizontal (round image)'
        targetEntityType: node
        cache: true
    core.entity_view_mode.node.sidebar_content:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.sidebar_content
        label: 'Sidebar Content'
        targetEntityType: node
        cache: true
    taxonomy.vocabulary.research_theme:
      createIfNotExists:
        langcode: en
        status: true
        dependencies: {  }
        name: 'Research Theme'
        vid: research_theme
        description: 'Associates the content with a research theme'
        weight: 0
    # assign ubc_profile permissions
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 2
        is_admin: false
      grantPermissions:
        - 'clone ubc_profile content'
        - 'create terms in research_theme'
        - 'delete terms in research_theme'
        - 'edit terms in research_theme'
    user.role.super_user:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: super_user
        label: 'Super User'
        weight: -5
        is_admin: false
      grantPermissions:
        - 'clone ubc_profile content'
        - 'create ubc_profile content'
        - 'delete any ubc_profile content'
        - 'delete own ubc_profile content'
        - 'delete ubc_profile revisions'
        - 'edit any ubc_profile content'
        - 'edit own ubc_profile content'
        - 'revert ubc_profile revisions'
        - 'view ubc_profile revisions'
        - 'create terms in research_theme'
        - 'delete terms in research_theme'
        - 'edit terms in research_theme'

