name: "Announcement type configuration"
description: "Announcement type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - image
  - link
  - menu_ui
  - node
  - path
  - taxonomy
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - field_group
  - focal_point
  - maxlength
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - pathauto
  - responsive_image
  - scheduler
  - simple_sitemap
  - text_summary_options
config:
  actions:
    # assign announcement permissions
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      grantPermissions:
        - 'create ubc_announcement content'
        - 'delete own ubc_announcement content'
        - 'delete ubc_announcement revisions'
        - 'edit own ubc_announcement content'
        - 'revert ubc_announcement revisions'
        - 'view ubc_announcement revisions'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create terms in announcement_type'
        - 'delete terms in announcement_type'
        - 'edit terms in announcement_type'
        - 'create ubc_announcement content'
        - 'delete any ubc_announcement content'
        - 'delete own ubc_announcement content'
        - 'delete ubc_announcement revisions'
        - 'edit any ubc_announcement content'
        - 'edit own ubc_announcement content'
        - 'revert ubc_announcement revisions'
        - 'view ubc_announcement revisions'
