name: "Event type configuration"
description: "Event type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - image
  - link
  - menu_ui
  - node
  - path
  - taxonomy
  - text
  - user
  - views
  # contrib
  - address
  - allowed_formats
  - datetime_range
  - datetimehideseconds
  - field_group
  - focal_point
  - maxlength
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - pathauto
  - responsive_image
  - scheduler
  - simple_sitemap
  - svg_image
  - text_summary_options
config:
  actions:
    # assign event permissions
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      grantPermissions:
        - 'create ubc_event content'
        - 'delete own ubc_event content'
        - 'delete ubc_event revisions'
        - 'edit own ubc_event content'
        - 'revert ubc_event revisions'
        - 'view ubc_event revisions'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create terms in event_category'
        - 'delete terms in event_category'
        - 'edit terms in event_category'
        - 'create ubc_event content'
        - 'delete any ubc_event content'
        - 'delete own ubc_event content'
        - 'delete ubc_event revisions'
        - 'edit any ubc_event content'
        - 'edit own ubc_event content'
        - 'revert ubc_event revisions'
        - 'view ubc_event revisions'
