name: "Event type configuration"
description: "Event type configuration recipe for UBC Web Services websites"
type: 'Content type'
recipes:
  - recipes/ws-recipes/taxonomy/taxonomy-event
install:
  #core
  - image
  - link
  - menu_ui
  - node
  - path
  - taxonomy
  - text
  - user
  - views
  # contrib
  - address
  - allowed_formats
  - datetime_range
  - datetimehideseconds
  - field_group
  - focal_point
  - maxlength
  - metatag
  - pathauto
  - responsive_image
  - scheduler
  - simple_sitemap
  - svg_image
  - text_summary_options
config:
  actions:
    # add view modes if they aren't present
    core.entity_view_mode.node.card_horizontal:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.card_horizontal
        label: 'Card: Horizontal'
        targetEntityType: node
        cache: true
    core.entity_view_mode.node.card_image:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.card_image
        label: 'Card: Image'
        targetEntityType: node
        cache: true
    core.entity_view_mode.node.card_vertical:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.card_vertical
        label: 'Card: Vertical'
        targetEntityType: node
        cache: true
    core.entity_view_mode.node.featured_content:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.featured_content
        label: 'Featured Content'
        targetEntityType: node
        cache: true
    # assign event permissions
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 1
        is_admin: false
      grantPermissions:
        - 'create ubc_event content'
        - 'delete own ubc_event content'
        - 'delete ubc_event revisions'
        - 'edit own ubc_event content'
        - 'revert ubc_event revisions'
        - 'view ubc_event revisions'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 2
        is_admin: false
      grantPermissions:
        - 'create ubc_event content'
        - 'delete any ubc_event content'
        - 'delete own ubc_event content'
        - 'delete ubc_event revisions'
        - 'edit any ubc_event content'
        - 'edit own ubc_event content'
        - 'revert ubc_event revisions'
        - 'view ubc_event revisions'
