name: "Profile type configuration"
description: "Profile type configuration recipe for UBC Web Services websites"
type: 'Content type'
recipes:
  - recipes/ws-recipes/taxonomy/taxonomy-department
install:
  #core
  - image
  - menu_ui
  - node
  - path
  - taxonomy
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - auto_entitylabel
  - field_group
  - maxlength
  - metatag
  - pathauto
  - scheduler
  - simple_sitemap
  - svg_image
  - telephone
  - text_summary_options
config:
  actions:
    # add view modes if they aren't present
    core.entity_view_mode.node.card_horizontal:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.card_horizontal
        label: 'Card: Horizontal'
        targetEntityType: node
        cache: true
    core.entity_view_mode.node.card_vertical:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.card_vertical
        label: 'Card: Vertical'
        targetEntityType: node
        cache: true
    # assign profile permissions
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 1
        is_admin: false
      grantPermissions:
        - 'create ubc_profile content'
        - 'delete own ubc_profile content'
        - 'delete ubc_profile revisions'
        - 'edit own ubc_profile content'
        - 'revert ubc_profile revisions'
        - 'view ubc_profile revisions'
    user.role.editor:
    # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 2
        is_admin: false
      grantPermissions:
        - 'create ubc_profile content'
        - 'delete any ubc_profile content'
        - 'delete own ubc_profile content'
        - 'delete ubc_profile revisions'
        - 'edit any ubc_profile content'
        - 'edit own ubc_profile content'
        - 'revert ubc_profile revisions'
        - 'view ubc_profile revisions'
