name: "Profile type configuration"
description: "Profile type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - image
  - menu_ui
  - node
  - path
  - taxonomy
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - auto_entitylabel
  - field_group
  - maxlength
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - pathauto
  - scheduler
  - simple_sitemap
  - svg_image
  - telephone
  - text_summary_options
config:
  actions:
    # assign profile permissions
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      grantPermissions:
        - 'create ubc_profile content'
        - 'delete own ubc_profile content'
        - 'delete ubc_profile revisions'
        - 'edit own ubc_profile content'
        - 'revert ubc_profile revisions'
        - 'view ubc_profile revisions'
    user.role.editor:
    # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create terms in department_or_unit'
        - 'delete terms in department_or_unit'
        - 'edit terms in department_or_unit'
        - 'create ubc_profile content'
        - 'delete any ubc_profile content'
        - 'delete own ubc_profile content'
        - 'delete ubc_profile revisions'
        - 'edit any ubc_profile content'
        - 'edit own ubc_profile content'
        - 'revert ubc_profile revisions'
        - 'view ubc_profile revisions'
