name: "Remote video media type"
description: "Base media types for UBC Web Services websites"
type: "Media type"
recipes:
  - core/recipes/remote_video_media_type
install:
  # core
  - file
  - image
  - responsive_image
  - media
  - media_library
  - path
  - user
config:
  actions:
    # alter default view mode for remote video media
    core.entity_view_display.media.remote_video.default:
      setComponents:
        -
          name: field_media_oembed_video
          options:
            type: oembed
            label: hidden
            settings:
              max_width: 900
              max_height: 506
              loading:
                attribute: lazy
            third_party_settings: {  }
            weight: 0
            region: content
        -
          name: thumbnail
          options:
            type: image
            label: hidden
            settings:
              image_link: ''
              image_style: video_thumbnail
              image_loading:
                attribute: lazy
            third_party_settings: {  }
            weight: 0
            region: content
    # assign remote_video media permissions
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      grantPermissions:
        - 'create remote_video media'
        - 'delete any remote_video media'
        - 'delete own remote_video media'
        - 'edit any remote_video media'
        - 'edit own remote_video media'
        - 'view any remote_video media revisions'
        - 'delete any remote_video media revisions'
        - 'revert any remote_video media revisions'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create remote_video media'
        - 'delete any remote_video media'
        - 'delete own remote_video media'
        - 'edit any remote_video media'
        - 'edit own remote_video media'
        - 'view any remote_video media revisions'
        - 'delete any remote_video media revisions'
        - 'revert any remote_video media revisions'