name: "Department or unit taxonomy"
description: "Department or unit taxonomy recipe for UBC Web Services websites"
type: "Taxonomy"
recipes:
  - recipes/ws-recipes/role/role-editor
install:
  # core
  - taxonomy
  # contrib
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - pathauto
config:
  # assign department taxonomy permissions
  actions:
    user.role.editor:
      grantPermissions:
        - 'create terms in department_or_unit'
        - 'delete terms in department_or_unit'
        - 'edit terms in department_or_unit'