name: "Department or unit taxonomy"
description: "Department or unit taxonomy recipe for UBC Web Services websites"
type: "Taxonomy"
install:
  # core
  - taxonomy
  - user
  # contrib
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - pathauto
config:
  # assign department taxonomy permissions
  actions:
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 2
        is_admin: false
      grantPermissions:
        - 'create terms in department_or_unit'
        - 'delete terms in department_or_unit'
        - 'edit terms in department_or_unit'