name: "Department or unit taxonomy"
description: "Department or unit taxonomy recipe for UBC Web Services websites"
type: "Taxonomy"
install:
  # core
  - taxonomy
  # contrib
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - pathauto