name: "Web Services VPR theme"
description: "Web Services VPR theme configuration for UBC Web Services websites"
type: "Site"
install:
  - vpr
config:
  import:
    vpr: "*"
  actions:
    system.theme:
      simple_config_update:
        default: vpr
