name: "Filtered text format"
description: "Filtered text format for UBC Web Services websites"
type: "Text format editor"
install:
  # core
  - ckeditor5
  - image
  - media
  - media_library
  - user
  # contrib
  - ckeditor5_fullscreen
  - ckeditor5_plugin_pack
  - ckeditor5_plugin_pack_bookmark
  - ckeditor5_plugin_pack_find_and_replace
  - ckeditor5_plugin_pack_indent_block
  - ckeditor5_plugin_pack_select_all
  - ckeditor5_plugin_pack_word_count
  - editor_advanced_link
  - linkit
  - responsive_table_filter
  - ubc_ckeditor_widgets
config:
  import:
    ckeditor5:
      - editor.editor.filtered_text.yml
      - filter.format.filtered_text.yml
    editor_advanced_link: "*"
    linkit: "*"
    responsive_table_filter: "*"
    ubc_ckeditor_widgets: "*"
  # assign text format permissions
  actions:
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      grantPermissions:
        - 'use text format filtered_text'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'use text format filtered_text'
