name: "Science Resource type configuration"
description: "Science Resource type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  # core
  - link
  - menu_ui
  - node
  - path
  - options
  - taxonomy
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - better_exposed_filters
  - maxlength
  - metatag
  - pathauto
  - scheduler
  - simple_sitemap
  - text_summary_options
config:
  actions:
    # assign science_resource permissions
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      grantPermissions:
        - 'create science_resource content'
        - 'delete own science_resource content'
        - 'delete science_resource revisions'
        - 'edit own science_resource content'
        - 'revert science_resource revisions'
        - 'view science_resource revisions'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create science_resource content'
        - 'delete any science_resource content'
        - 'delete own science_resource content'
        - 'delete science_resource revisions'
        - 'edit any science_resource content'
        - 'edit own science_resource content'
        - 'revert science_resource revisions'
        - 'view science_resource revisions'
        - 'create terms in research_type'
        - 'delete terms in research_type'
        - 'edit terms in research_type'
    user.role.manager:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: manager
        label: 'Manager'
        weight: 7
        is_admin: false
      grantPermissions:
        - 'create science_resource content'
        - 'delete any science_resource content'
        - 'delete own science_resource content'
        - 'delete science_resource revisions'
        - 'edit any science_resource content'
        - 'edit own science_resource content'
        - 'revert science_resource revisions'
        - 'view science_resource revisions'
        - 'create terms in research_type'
        - 'delete terms in research_type'
        - 'edit terms in research_type'

