name: "Paragraph configuration"
description: "Paragraph configuration recipe for UBC Web Services websites"
type: "Paragraph configuration"
recipes:
  - recipes/ws-recipes/role/role-editor
  - recipes/ws-recipes/role/role-content-creator
  - recipes/ws-recipes/paragraphs/paragraph-card-group
  - recipes/ws-recipes/paragraphs/paragraph-feature-image
  - recipes/ws-recipes/paragraphs/paragraph-slideshow
  - recipes/ws-recipes/paragraphs/paragraph-tabcordion
  - recipes/ws-recipes/paragraphs/paragraph-text
config:
  # assign general paragraphs permissions
  actions:
    user.role.content_creator:
      grantPermissions:
        - 'view unpublished paragraphs'
    user.role.editor:
      grantPermissions:
        - 'view unpublished paragraphs'