name: "Video media type"
description: "Video media type recipe for UBC Web Services websites"
type: "Media"
recipes:
  - core/recipes/local_video_media_type
install:
  # core
  - file
  - image
  - media
  - path
  - user
config:
  actions:
    # update the path where media is is stored
    field.field.media.video.field_media_video_file:
      simpleConfigUpdate:
        settings.file_directory: media-uploads/video
    # assign video media permissions
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create video media'
        - 'delete any video media'
        - 'delete own video media'
        - 'edit any video media'
        - 'edit own video media'
        - 'view any video media revisions'
        - 'delete any video media revisions'
        - 'revert any video media revisions'
