
name: "VPR Announcement type configuration"
description: "VPR Announcement type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - datetime
  - image
  - link
  - menu_ui
  - node
  - options
  - path
  - responsive_image
  - taxonomy
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - entity_reference_revisions
  - field_group
  - focal_point
  - maxlength
  - metatag
  - paragraphs
  - pathauto
  - quick_node_clone
  - scheduler
  - simple_sitemap
  - text_summary_options
config:
  actions:
    # update the form display
    core.entity_form_display.node.ubc_announcement.default:
      setComponents:
        -
          name: field_announcement_custom_conten
          options:
            type: paragraphs
            weight: 3
            region: content
            settings:
              title: Paragraph
              title_plural: Paragraphs
              edit_mode: closed
              closed_mode: summary
              autocollapse: none
              closed_mode_threshold: 0
              add_mode: dropdown
              form_display_mode: default
              default_paragraph_type: _none
              features:
                add_above: add_above
                collapse_edit_all: collapse_edit_all
                convert: convert
                duplicate: duplicate
            third_party_settings: {  }
        -
          name: field_announcement_image_teaser
          options:
            type: string_textfield
            weight: 1
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings:
              maxlength:
                maxlength_js: 120
                maxlength_js_label: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
        -
          name: field_show_gradient_on_image
          options:
            type: boolean_checkbox
            weight: 1
            region: content
            settings:
              display_label: true
            third_party_settings: {  }
    # update the featured content display
    core.entity_view_display.node.ubc_announcement.featured_content:
      setComponent:
        name: field_announcement_image_teaser
        options:
          type: string
          weight: 1
          region: content
          label: hidden
          settings:
            link_to_entity: false
          third_party_settings: {  }
    # update the teaser display
    core.entity_view_display.node.ubc_announcement.teaser:
      setComponent:
        name: field_announcement_external_link
        options:
          type: link
          weight: 2
          region: content
          label: hidden
          settings:
            trim_length: 80
            url_only: false
            url_plain: false
            rel: ''
            target: ''
          third_party_settings: {  }
    # assign ubc_announcement permissions
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'clone ubc_announcement content'
        - 'create terms in research_theme'
        - 'delete terms in research_theme'
        - 'edit terms in research_theme'
        - 'create terms in announcement_type'
        - 'delete terms in announcement_type'
        - 'edit terms in announcement_type'
    user.role.super_user:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: super_user
        label: 'Super User'
        weight: 7
        is_admin: false
      grantPermissions:
        - 'clone ubc_announcement content'
        - 'create ubc_announcement content'
        - 'delete any ubc_announcement content'
        - 'delete own ubc_announcement content'
        - 'delete ubc_announcement revisions'
        - 'edit any ubc_announcement content'
        - 'edit own ubc_announcement content'
        - 'revert ubc_announcement revisions'
        - 'view ubc_announcement revisions'
        - 'create terms in research_theme'
        - 'delete terms in research_theme'
        - 'edit terms in research_theme'
        - 'create terms in announcement_type'
        - 'delete terms in announcement_type'
        - 'edit terms in announcement_type'