
name: "Science Homepage type configuration"
description: "Science Homepage type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - datetime
  - image
  - link
  - menu_ui
  - node
  - options
  - path
  - responsive_image
  - taxonomy
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - entity_reference_revisions
  - field_group
  - focal_point
  - maxlength
  - metatag
  - pathauto
  - paragraphs
  - scheduler
  - simple_sitemap
  - text_summary_options
  - ubc_science_nodes
config:
  actions:
    # update field settings
    field.field.node.homepage.field_home_feature_image:
      simple_config_update:
        required: false
    # update the form display
    core.entity_form_display.node.homepage.default:
      simple_config_update:
        content.title.weight: -10
        hidden.field_feature_link: true
        hidden.field_feature_text: true
        hidden.field_home_feature_image: true
        third_party_settings.field_group.group_feature_area.children: { }
      setComponents:
        -
          name: field_homepage_custom_content
          options:
            type: paragraphs
            weight: 3
            region: content
            settings:
              title: Paragraph
              title_plural: Paragraphs
              edit_mode: open
              closed_mode: 'summary'
              autocollapse: 'none'
              closed_mode_threshold: 0
              add_mode: button
              form_display_mode: default
              default_paragraph_type: none
              features:
                add_above: 'add_above'
                collapse_edit_all: 'collapse_edit_all'
                duplicate: 'duplicate'
            third_party_settings: {  }
        -
          name: field_homepage_masthead
          options:
            type: paragraphs
            weight: 1
            region: content
            settings:
              title: Masthead
              title_plural: 'Mastheads'
              edit_mode: open
              closed_mode: 'summary'
              autocollapse: 'none'
              closed_mode_threshold: 0
              add_mode: button
              form_display_mode: default
              default_paragraph_type: none
              features:
                add_above: 0
                collapse_edit_all: 'collapse_edit_all'
                duplicate: 'duplicate'
            third_party_settings: {  }
    # update the default display
    core.entity_view_display.node.homepage.default:
      simple_config_update:
        hidden.field_homepage_masthead: true
    # update the featured_content display
    core.entity_view_display.node.homepage.featured_content:
      simple_config_update:
        hidden.field_feature_link: true
        hidden.field_feature_text: true
        hidden.field_home_feature_image: true
        hidden.links: true
      setComponent:
        name: field_homepage_masthead
        options:
          type: entity_reference_revisions_entity_view
          weight: 0
          label: hidden
          region: content
          settings:
            view_mode: default
            link: false
          third_party_settings: { }
    # assign homepage permissions
    user.role.manager:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: manager
        label: 'Manager'
        weight: 7
        is_admin: false
      grantPermissions:
        - 'delete homepage revisions'
        - 'edit any homepage content'
        - 'edit own homepage content'
        - 'revert homepage revisions'
        - 'view homepage revisions'
