name: "Content Creator role"
description: "Content Creator role recipe for UBC Web Services websites"
type: "User role"
install:
  # core
  - file
  - menu_ui
  - path
  - taxonomy
  - toolbar
config:
  actions:
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 1
        is_admin: false
      # grant permissions from enabled core modules
      grantPermissions:
        - 'access administration pages'
        - 'access content overview'
        - 'access files overview'
        - 'access site in maintenance mode'
        - 'access taxonomy overview'
        - 'access toolbar'
        - 'administer menu'
        - 'administer url aliases'
        - 'create url aliases'
        - 'view the administration theme'
