
name: "VPR Landing Page type configuration"
description: "VPR Landing Page type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - datetime
  - image
  - link
  - menu_ui
  - node
  - options
  - path
  - responsive_image
  - taxonomy
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - entity_reference_revisions
  - field_group
  - focal_point
  - maxlength
  - metatag
  - pathauto
  - paragraphs
  - quick_node_clone
  - scheduler
  - simple_sitemap
  - text_summary_options
config:
  actions:
    field.storage.node.field_show_gradient_on_image:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.field_show_gradient_on_image
        field_name: field_show_gradient_on_image
        entity_type: node
        type: boolean
        settings: {  }
        module: core
        locked: false
        cardinality: 1
        translatable: true
        indexes: {  }
        persist_with_no_fields: false
        custom_storage: false
    # add view modes if they aren't present
    core.entity_view_mode.node.sidebar_content:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.card_horizontal
        label: 'Card: Horizontal'
        targetEntityType: node
        cache: true
    # assign ubc_landing_page permissions
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 2
        is_admin: false
      grantPermissions:
        - 'clone ubc_landing_page content'
    user.role.super_user:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: super_user
        label: 'Super User'
        weight: -5
        is_admin: false
      grantPermissions:
        - 'clone ubc_landing_page content'
        - 'create ubc_landing_page content'
        - 'delete any ubc_landing_page content'
        - 'delete own ubc_landing_page content'
        - 'delete ubc_landing_page revisions'
        - 'edit any ubc_landing_page content'
        - 'edit own ubc_landing_page content'
        - 'revert ubc_landing_page revisions'
        - 'view ubc_landing_page revisions'
