name: "Add bookmark button to toolbar"
description: "Add bookmark button to toolbar for UBC Web Services websites"
type: "Text format"
install:
  # core
  - ckeditor5
  # contrib
  - ckeditor5_plugin_pack
  - ckeditor5_plugin_pack_bookmark
config:
  actions:
    editor.editor.filtered_text:
      addItemToToolbar:
        item_name: bookmark
        # Specific zero-based position in the toolbar.
        # If not specified, it appends to the end.
        position: 4
        replace: false
