name: "Web Services UBC theme"
description: "Web Services UBC theme configuration for UBC Web Services websites"
type: "Site"
install:
  - kraken
config:
  import:
    kraken: "*"
  actions:
    system.theme:
      simple_config_update:
        default: kraken
