name: "Blog type configuration"
description: "Blog type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - datetime
  - image
  - link
  - menu_ui
  - node
  - options
  - path
  - responsive_image
  - taxonomy
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - field_group
  - focal_point
  - maxlength
  - metatag
  - pathauto
  - scheduler
  - simple_sitemap
  - text_summary_options
config:
  actions:
    # assign awards permissions
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      grantPermissions:
        - 'create ubc_blog content'
        - 'delete own ubc_blog content'
        - 'delete ubc_blog revisions'
        - 'edit own ubc_blog content'
        - 'revert ubc_blog revisions'
        - 'view ubc_blog revisions'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create ubc_blog content'
        - 'delete any ubc_blog content'
        - 'delete own ubc_blog content'
        - 'delete ubc_blog revisions'
        - 'edit any ubc_blog content'
        - 'edit own ubc_blog content'
        - 'revert ubc_blog revisions'
        - 'view ubc_blog revisions'
    user.role.manager:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: manager
        label: 'Manager'
        weight: 7
        is_admin: false
      grantPermissions:
        - 'create ubc_blog content'
        - 'delete any ubc_blog content'
        - 'delete own ubc_blog content'
        - 'delete ubc_blog revisions'
        - 'edit any ubc_blog content'
        - 'edit own ubc_blog content'
        - 'revert ubc_blog revisions'
        - 'view ubc_blog revisions'
