name: "Vertical card paragraph"
description: "Vertical card paragraph recipe for UBC Web Services websites"
type: "Paragraph type"
install:
  # core
  - file
  - image
  - breakpoint
  - link
  - responsive_image
  - taxonomy
  # contrib
  - entity_reference_revisions
  - focal_point
  - maxlength
  - paragraphs
  - ubc_paragraph_entities
