
name: "Science Profile type configuration"
description: "Science Profile type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - image
  - link
  - menu_ui
  - node
  - options
  - path
  - responsive_image
  - taxonomy
  - telephone
  - text
  - user
  - views
  # contrib
  - address
  - allowed_formats
  - conditional_fields
  - field_group
  - focal_point
  - maxlength
  - metatag
  - pathauto
  - scheduler
  - simple_sitemap
  - text_summary_options
config:
  actions:
    # update fields
    field.field.node.ubc_profile.field_profile_accreditation:
      simple_config_update:
        label: 'Accreditation, Credentials'
    field.field.node.ubc_profile.field_profile_image:
      simple_config_update:
        settings.file_extensions: 'png jpg jpeg'
    # update the form display
    core.entity_form_display.node.ubc_profile.default:
      simple_config_update:
        hidden.field_profile_office: true
        third_party_settings.field_group.group_metadata.children:
          - field_profile_department_unit
          - field_profile_address_tax
          - field_profile_type
          - field_profile_program
          - field_profile_year
          - field_profile_rank
          - field_profile_tags
      setComponents:
        -
          name: field_profile_address_tax
          options:
            type: options_select
            weight: 5
            region: content
            settings: { }
            third_party_settings: {  }
        -
          name: field_profile_department_unit
          options:
            type: options_select
            weight: 4
            region: content
            settings: { }
            third_party_settings: {  }
        -
          name: field_profile_job_title
          options:
            type: string_textfield
            weight: 4
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings:
              maxlength:
                maxlength_js: 255
                maxlength_js_label: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
              conditional_fields : { }
        -
          name: field_profile_program
          options:
            type: string_textfield
            weight: 30
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings:
              maxlength:
                maxlength_js: 255
                maxlength_js_label: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
                maxlength_js_enforce: false
              conditional_fields : { }
        -
          name: field_profile_rank
          options:
            type: options_select
            weight: 32
            region: content
            settings: { }
            third_party_settings: {  }
        -
          name: field_profile_sidebar_links
          options:
            type: link_default
            weight: 10
            region: content
            settings:
              placeholder_url: ''
              placeholder_title: ''
            third_party_settings:
              maxlength:
                maxlength_js: 100
                maxlength_js_label: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
              conditional_fields : { }
        -
          name: field_profile_type
          options:
            type: options_select
            weight: 6
            region: content
            settings: { }
            third_party_settings: {  }
        -
          name: field_profile_year
          options:
            type: number
            weight: 31
            region: content
            settings:
              placeholder: ''
            third_party_settings:
              maxlength:
                conditional_fields: { }
    # update the default display
    core.entity_view_display.node.ubc_profile.default:
      setComponents:
        -
          name: field_profile_address_tax
          options:
            type: entity_reference_label
            weight: 16
            region: content
            label: hidden
            settings:
              link: false
            third_party_settings: { }
        -
          name: field_profile_rank
          options:
            type: entity_reference_label
            weight: 13
            region: content
            label: hidden
            settings:
              link: false
            third_party_settings: { }
        -
          name: field_profile_type
          options:
            type: entity_reference_label
            weight: 14
            region: content
            label: hidden
            settings:
              link: false
            third_party_settings: { }
        -
          name: field_profile_sidebar_links
          options:
            type: link
            weight: 10
            region: content
            label: hidden
            settings:
              trim_length: 80
              url_only: false
              url_plain: false
              rel: ''
              target: ''
            third_party_settings: { }
        -
          name: field_profile_program
          options:
            type: string
            weight: 17
            region: content
            label: hidden
            settings:
              link_to_entity: false
        -
          name: field_profile_year
          options:
            type: number_integer
            weight: 18
            region: content
            label: hidden
            settings:
              thousand_separator: ''
              prefix_suffix: true
            third_party_settings: { }
    # update the card_horizontal display
    core.entity_view_display.node.ubc_profile.card_horizontal:
      simple_config_update:
        hidden.body: true
        hidden.field_profile_address_tax: true
        hidden.field_profile_email: true
        hidden.field_profile_first_name: true
        hidden.field_profile_last_name: true
        hidden.field_profile_meta_tags: true
        hidden.field_profile_office: true
        hidden.field_profile_phone: true
        hidden.field_profile_program: true
        hidden.field_profile_pronouns: true
        hidden.field_profile_rank: true
        hidden.field_profile_sidebar_links: true
        hidden.field_profile_tags: true
        hidden.field_profile_type: true
        hidden.field_profile_year: true
        hidden.links: true
    # update the card_vertical display
    core.entity_view_display.node.ubc_profile.card_vertical:
      simple_config_update:
        hidden.body: true
        hidden.field_profile_address_tax: true
        hidden.field_profile_email: true
        hidden.field_profile_first_name: true
        hidden.field_profile_last_name: true
        hidden.field_profile_meta_tags: true
        hidden.field_profile_office: true
        hidden.field_profile_phone: true
        hidden.field_profile_program: true
        hidden.field_profile_pronouns: true
        hidden.field_profile_rank: true
        hidden.field_profile_sidebar_links: true
        hidden.field_profile_tags: true
        hidden.field_profile_type: true
        hidden.field_profile_year: true
        hidden.links: true
      setComponent:
        name: field_profile_image
        options:
          type: image
          weight: 0
          label: hidden
          region: content
          settings:
            image_link: ''
            image_style: landscape_600x400_focal_point
            svg_attributes:
              width: null
              height: null
            svg_render_as_image: true
            image_loading:
              attribute: lazy
          third_party_settings: {  }
    # update the teaser display
    core.entity_view_display.node.ubc_profile.teaser:
      simple_config_update:
        hidden.body: true
        hidden.field_profile_accreditation: true
        hidden.field_profile_address_tax: true
        hidden.field_profile_first_name: true
        hidden.field_profile_image: true
        hidden.field_profile_last_name: true
        hidden.field_profile_meta_tags: true
        hidden.field_profile_office: true
        hidden.field_profile_program: true
        hidden.field_profile_pronouns: true
        hidden.field_profile_rank: true
        hidden.field_profile_sidebar_links: true
        hidden.field_profile_tags: true
        hidden.field_profile_type: true
        hidden.field_profile_year: true
        hidden.links: true
    # assign ubc_profile permissions
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'create terms in addresses'
        - 'delete terms in addresses'
        - 'edit terms in addresses'
        - 'create terms in department_or_unit'
        - 'delete terms in department_or_unit'
        - 'edit terms in department_or_unit'
        - 'create terms in profile_rank'
        - 'delete terms in profile_rank'
        - 'edit terms in profile_rank'
        - 'create terms in profile_type'
        - 'delete terms in profile_type'
        - 'edit terms in profile_type'
    user.role.manager:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: manager
        label: 'Manager'
        weight: 7
        is_admin: false
      grantPermissions:
        - 'create ubc_profile content'
        - 'delete any ubc_profile content'
        - 'delete own ubc_profile content'
        - 'delete ubc_profile revisions'
        - 'edit any ubc_profile content'
        - 'edit own ubc_profile content'
        - 'revert ubc_profile revisions'
        - 'view ubc_profile revisions'
        - 'create terms in addresses'
        - 'delete terms in addresses'
        - 'edit terms in addresses'
        - 'create terms in department_or_unit'
        - 'delete terms in department_or_unit'
        - 'edit terms in department_or_unit'
        - 'create terms in profile_rank'
        - 'delete terms in profile_rank'
        - 'edit terms in profile_rank'
        - 'create terms in profile_type'
        - 'delete terms in profile_type'
        - 'edit terms in profile_type'

