name: "Image card paragraph"
description: "Image card paragraph recipe for UBC Web Services websites"
type: "Paragraph type"
install:
  # core
  - file
  - image
  - link
  - responsive_image
  - taxonomy
  # contrib
  - maxlength
  - paragraphs
  - svg_image
  - ubc_paragraph_entities
