name: "Science Filtered text format"
description: "Science Filtered text format for UBC Web Services websites"
type: "Text format editor"
install:
  # core
  - ckeditor5
  - image
  - media
  - media_library
  - user
  # contrib
  - ckeditor5_fullscreen
  - editor_advanced_link
  - linkit
  - responsive_table_filter
  - ubc_ckeditor_widgets
config:
  actions:
    # Update text format config
    editor.editor.filtered_text:
      simple_config_update:
        settings.plugins.ckeditor5_style.styles:
          -
            label: 'Lead Text'
            element: '<p class="text-lead text-ubc-blue-sea">'
          -
            label: 'Text: small'
            element: '<p class="text-sm">'
          -
            label: 'Serif font'
            element: '<p class="font-serif">'
          -
            label: 'Uppercase Text'
            element: '<span class="text-uppercase">'
          -
            label: 'Lowercase Text'
            element: '<span class="text-lowercase">'
          -
            label: 'Semibold Text'
            element: '<span class="font-semibold">'
          -
            label: 'Grey Text'
            element: '<span class="text-grey-700">'
          -
            label: 'White Text'
            element: '<span class="text-white">'
          -
            label: 'Attribution, Footnote Text'
            element: '<p class="text-sm text-grey-700 text-uppercase">'
          -
            label: 'List: inline'
            element: '<ul class="list-inline">'
          -
            label: 'List: bordered'
            element: '<ul class="list-bordered">'
          -
            label: 'List: checked'
            element: '<ul class="list-checked">'
          -
            label: 'List: buttons'
            element: '<ul class="button-list">'
          -
            label: 'List: 2 across'
            element: '<ul class="button-list list-grid--two">'
          -
            label: 'List: 3 across'
            element: '<ul class="button-list list-grid--three">'
          -
            label: 'List: 4 across'
            element: '<ul class="button-list list-grid--four">'
          -
            label: 'Ordered List: inline'
            element: '<ol class="list-inline">'
          -
            label: 'Ordered List: bordered'
            element: '<ol class="list-bordered">'
          -
            label: 'Ordered List: checked'
            element: '<ol class="list-checked">'
          -
            label: 'Ordered List: buttons'
            element: '<ol class="button-list">'
          -
            label: 'Ordered List: 2 across'
            element: '<ol class="button-list list-grid--two">'
          -
            label: 'Ordered List: 3 across'
            element: '<ol class="button-list list-grid--three">'
          -
            label: 'Ordered List: 4 across'
            element: '<ol class="button-list list-grid--four">'
          -
            label: 'Unit Button'
            element: '<a class="unit-button">'
          -
            label: 'Light Button'
            element: '<a class="unit-button unit-button--light">'
          -
            label: 'Dark Button'
            element: '<a class="unit-button unit-button--dark">'
          -
            label: 'Simple Button'
            element: '<a class="unit-button unit-button--simple">'
          -
            label: 'Bordered Button'
            element: '<a class="unit-button unit-button--bordered">'
          -
            label: 'Subunit Button'
            element: '<a class="unit-button unit-button--subunit">'
          -
            label: 'Transparent Button'
            element: '<a class="unit-button unit-button--transparent">'
          -
            label: 'Capped Button'
            element: '<a class="unit-button unit-button--capped">'
          -
            label: 'Full-width Button'
            element: '<a class="unit-button unit-button--block">'
          -
            label: 'Extra Small Button'
            element: '<a class="text-xs unit-button unit-button--text-xs">'
          -
            label: 'Small Button'
            element: '<a class="text-sm unit-button unit-button--text-sm">'
          -
            label: 'Large Button'
            element: '<a class="text-lg unit-button unit-button--text-lg">'
          -
            label: 'XLarge Button'
            element: '<a class="text-xl unit-button unit-button--text-xl">'
          -
            label: 'XXLarge Button'
            element: '<a class="text-2xl unit-button unit-button--text-2xl">'
          -
             label: 'Hidden Anchor'
             element: '<a class="sr-only anchor anchor-invisible">'