name: "Web Services Science theme"
description: "Web Services Science theme configuration for UBC Web Services websites"
type: "Site"
install:
  - science
config:
  import:
    science: "*"
  actions:
    system.theme:
      simple_config_update:
        default: science
