name: "Text paragraph"
description: "Text paragraph recipe for UBC Web Services websites"
type: "Paragraph type"
install:
  # core
  - taxonomy
  - text
  # contrib
  - entity_reference_revisions
  - paragraphs
  - ubc_paragraph_entities
