name: "Text paragraph"
description: "Text paragraph recipe for UBC Web Services websites"
type: "Paragraph type"
recipes:
  - recipes/ws-recipes/taxonomy/taxonomy-admin
  - recipes/ws-recipes/paragraphs/paragraph-shared-fields
install:
  # core
  - taxonomy
  - text
  # contrib
  - entity_reference_revisions
  - paragraphs
  - ubc_paragraph_entities
