name: "Web Services VPR theme"
description: "Web Services VPR theme configuration for UBC Web Services websites"
type: "Site"
install:
  - vpr
config:
  import:
    vpr: "*"
  actions:
    system.theme:
      simple_config_update:
        default: vpr
    block.block.vpr_help:
      simple_config_update:
        region: help
    block.block.vpr_messages:
      simple_config_update:
        region: help
    # disable unneeded blocks
    block.block.vpr_page_title:
      simple_config_update:
        status: false
    block.block.vpr_powered:
      simple_config_update:
        status: false
    block.block.vpr_search_form_wide:
      simple_config_update:
        status: false
    block.block.vpr_search_form_narrow:
      simple_config_update:
        status: false
    block.block.vpr_account_menu:
      simple_config_update:
        status: false
    block.block.vpr_syndicate:
      simple_config_update:
        status: false
    block.block.vpr_site_branding:
      simple_config_update:
        status: false
    block.block.vpr_content:
      simple_config_update:
        status: false
    block.block.vpr_primary_admin_actions:
      simple_config_update:
        status: false
    block.block.vpr_primary_local_tasks:
      simple_config_update:
        status: false
