name: "Homepage type configuration"
description: "Homepage type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - file
  - image
  - link
  - menu_ui
  - node
  - path
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - entity_reference_revisions
  - field_group
  - focal_point
  - maxlength
  - metatag
  - paragraphs
  - pathauto
  - responsive_image
  - scheduler
  - simple_sitemap
  - text_summary_options
config:
  actions:
    # add view modes if they aren't present
    core.entity_view_mode.node.custom_content:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.custom_content
        label: 'Custom Content'
        targetEntityType: node
        cache: true
    core.entity_view_mode.node.featured_content:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - node
        id: node.featured_content
        label: 'Featured Content'
        targetEntityType: node
        cache: true
    # assign homepage permissions
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 2
        is_admin: false
      grantPermissions:
        - 'delete homepage revisions'
        - 'edit any homepage content'
        - 'edit own homepage content'
        - 'revert homepage revisions'
        - 'view homepage revisions'
