
name: "VPR Webform type configuration"
description: "VPR Webform type configuration recipe for UBC Web Services websites"
type: 'Content type'
install:
  #core
  - datetime
  - image
  - link
  - menu_ui
  - node
  - options
  - path
  - responsive_image
  - taxonomy
  - text
  - user
  - views
  # contrib
  - allowed_formats
  - field_group
  - focal_point
  - maxlength
  - metatag
  - pathauto
  - quick_node_clone
  - scheduler
  - simple_sitemap
  - text_summary_options
  - webform
  - webform_node
config:
  import:
    webform_node: "*"
  actions:
    # update the form display
    core.entity_form_display.node.webform.default:
      simple_config_update:
        third_party_settings.field_group.group_metadata:
          children:
            - field_webform_tags
          label:  'Metadata'
          region: 'content'
          parent_name: ''
          weight: '11'
          format_type: 'details_sidebar'
          format_settings:
            classes: ''
            show_empty_fields: false
            id: ''
            open: true
            description: ''
            required_fields: true
            weight: '-100'
      setComponents:
        -
          name: body
          options:
            type: text_textarea_with_summary
            weight: 1
            region: content
            settings:
              rows: 9
              placeholder: ''
              summary_rows: 3
              show_summary: true
            third_party_settings:
              maxlength:
                maxlength_js: ''
                maxlength_js_label: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
                maxlength_js_summary: 160
                maxlength_js_label_summary: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
                maxlength_js_enforce: true
                maxlength_js_truncate_html: false
              allowed_formats:
                hide_help: 0
                hide_guidelines: 0
        -
          name: field_webform_tags
          options:
            type: options_select
            weight: 26
            region: content
            settings: { }
            third_party_settings: {  }
        -
          name: field_webform_meta_tags
          options:
            type: metatag_firehose
            weight: 13
            region: content
            settings:
              sidebar: true
              use_details: true
            third_party_settings: {  }
        -
          name: field_webform_supporting_content
          options:
            type: text_textarea
            weight: 3
            region: content
            settings:
              rows: 5
              placeholder: ''
            third_party_settings:
              maxlength:
                maxlength_js: ''
                maxlength_js_label: 'Content limited to @limit characters, remaining: <strong>@remaining</strong>'
                maxlength_js_enforce: false
                maxlength_js_truncate_html: false
              allowed_formats:
                hide_help: 0
                hide_guidelines: 0
    # assign webform permissions
    user.role.content_creator:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: content_creator
        label: Content Creator
        weight: 5
        is_admin: false
      grantPermissions:
        - 'create webform content'
        - 'delete own webform content'
        - 'delete webform revisions'
        - 'edit own webform content'
        - 'revert webform revisions'
        - 'view webform revisions'
    user.role.editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: editor
        label: Editor
        weight: 6
        is_admin: false
      grantPermissions:
        - 'clone webform content'
        - 'create webform content'
        - 'delete any webform content'
        - 'delete own webform content'
        - 'delete webform revisions'
        - 'edit any webform content'
        - 'edit own webform content'
        - 'revert webform revisions'
        - 'view webform revisions'
    user.role.super_user:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: super_user
        label: 'Super User'
        weight: 7
        is_admin: false
      grantPermissions:
        - 'clone webform content'
        - 'create webform content'
        - 'delete any webform content'
        - 'delete own webform content'
        - 'delete webform revisions'
        - 'edit any webform content'
        - 'edit own webform content'
        - 'revert webform revisions'
        - 'view webform revisions'
