
name: "Chosen settings - update configuration"
description: "Chosen settings - update configuration for UBC Web Services websites"
type: 'Config'
config:
  actions:
    # chosen settings
    chosen.settings:
      simple_config_update:
        jquery_selector: 'select:not(:where(.webform-ui-element-form *))'
