name: "VPR Homepage default content configuration"
description: "VPR Homepage default content recipe for UBC Web Services websites"
type: "Content"
recipes:
  - recipes/ws-recipes/portfolio/portfolio-vpr/node/node-vpr-homepage