name: "Add findreplace button to toolbar"
description: "Add findreplace button to toolbar for UBC Web Services websites"
type: "Text format"
install:
  # core
  - ckeditor5
  # contrib
  - ckeditor5_plugin_pack
  - ckeditor5_plugin_pack_find_and_replace
config:
  actions:
    # enable standalone media settings
    editor.editor.filtered_text:
      addItemToToolbar:
        item_name: findAndReplace
        # Specific zero-based position in the toolbar.
        # If not specified, it appends to the end.
        replace: false
